variables:
  GITLAB_TOKEN: $GL_TOKEN

include:
  # 1: include the component
  - component: $CI_SERVER_FQDN/to-be-continuous/semantic-release/gitlab-ci-semrel@3.13.0
    # 2: set/override component inputs
    inputs:
      changelog-enabled: true # ⚠ this is only an example
      commit-spec: conventionalcommits
